enable perl and shell linting for `opennms-repo`
OpenNMS/opennms-repo pull request #115
Opened 2022-12-02 18:58 UTC by RangerRick

do some basic linting in CircleCI

2022-12-02 18:59 UTC, RangerRick commented
this builds on my previous PR [here](https://github.com/OpenNMS/opennms-repo/pull/114) -- that should be merged first

2022-12-03 05:20 UTC, deejgregor requested changes
I think a few variables were mistakenly changed. See per-line comments.

2022-12-03 05:20 UTC, deejgregor commented on script/deploy-debs.pl
> +		push(@$FILEDIR_HANDLE_DEBS, $line);
I think this was mistakenly changed.

2022-12-03 05:20 UTC, deejgregor commented on script/deploy-rpms.pl
> +		push(@$FILEDIR_HANDLE_RPMS, $line);
I think this was mistakenly changed.

2022-12-03 05:20 UTC, deejgregor commented on script/update-doc-repo.pl
> +		my $target = File::Spec->catdir($INSTALL$DOCDIR_HANDLE, $name);
I think this was mistakenly changed.

2022-12-03 05:20 UTC, deejgregor commented on script/update-doc-repo.pl
> +		my $tocommon = File::Spec->catdir($INSTALL$DIR_HANDLE, '.common');
I think this was mistakenly changed.

2022-12-03 05:20 UTC, deejgregor commented on script/update-doc-repo.pl
> +		my $to = File::Spec->catdir($INSTALL$DIR_HANDLE, $mappedname);
I think this was mistakenly changed.

2022-12-03 05:54 UTC, deejgregor commented on script/deploy-debs.pl
> +		push(@$FILEDIR_HANDLE_DEBS, $line);
I went ahead and pushed the fix for this in 09221ba03061f827f11745fc76aa389094aefa11.

2022-12-03 05:54 UTC, deejgregor commented on script/deploy-rpms.pl
> +		push(@$FILEDIR_HANDLE_RPMS, $line);
I went ahead and pushed the fix for this in 09221ba03061f827f11745fc76aa389094aefa11.

2022-12-03 05:54 UTC, deejgregor commented on script/update-doc-repo.pl
> +		my $target = File::Spec->catdir($INSTALL$DOCDIR_HANDLE, $name);
I went ahead and pushed the fix for this in 09221ba03061f827f11745fc76aa389094aefa11.

2022-12-03 05:55 UTC, deejgregor commented on script/update-doc-repo.pl
> +		my $to = File::Spec->catdir($INSTALL$DIR_HANDLE, $mappedname);
I went ahead and pushed the fix for this in 09221ba03061f827f11745fc76aa389094aefa11.

2022-12-03 05:56 UTC, deejgregor approved these changes
I think this is ready to go!

I went ahead and pushed a few fixes in 09221ba03061f827f11745fc76aa389094aefa11.

2022-12-05 15:36 UTC, RangerRick commented
Good catch, clearly this was a PR I pushed on a friday afternoon and didn't want to lose, but still needed to look over. ;)

2022-12-05 15:36 UTC, merged